from PyQt5.QtWidgets import (QMainWindow, QFileDialog)
from wppublisher.ui import generated

'''
The qt gui class is generated by pyuic5
Due to it being a generated class, it is not edited directly.
Instead, this class wraps around it.
'''
class wp_gui(QMainWindow):
    def __init__(self):
        super().__init__()
        self.init_ui()

    def init_ui(self):
        self.ui = generated.Ui_MainWindow()
        self.ui.setupUi(self)

        installation_path_selector = self.ui.installation_path_file_selector
        installation_path_selector.clicked.connect(self.set_installation_path)
        self.show()

    def set_installation_path(self):
        folder_name = QFileDialog.getExistingDirectory(self, 'Select the folder where you would like to install wordpress')
        installation_path = self.ui.installation_path_text
        installation_path.setText(folder_name)

        '''
        if fname[0]:
            f = open(fname[0], 'r')

            with f:
                data = f.read()
                self.textEdit.setText(data)
        '''
