import sys
from PyQt5.QtWidgets import (QMainWindow, QTextEdit,
                             QAction, QFileDialog, QApplication)
from PyQt5.QtGui import QIcon
from wppublisher.ui import generated

'''
The qt gui class is generated by pyuic5
Due to it being a generated class, it is not edited directly.
Instead, this class wraps around it.
'''
class wp_gui(QMainWindow):
    def __init__(self):
        super().__init__()

        self.initUI()

    def initUI(self):
        ui = generated.Ui_MainWindow()
        ui.setupUi(self)

        start_button = ui.installation_start_button
        start_button.clicked.connect(self.showDialog)
        self.show()

    def showDialog(self):
        fname = QFileDialog.getOpenFileName(self, 'Open file', '/home')

        '''
        if fname[0]:
            f = open(fname[0], 'r')

            with f:
                data = f.read()
                self.textEdit.setText(data)
        '''
