import datetime
import os
import re

from PyQt5.QtCore import *
from PyQt5.QtWidgets import (QMainWindow, QFileDialog, QMessageBox)


import generated
import publish
import wordpress
import workers


class Fields():
    def __init__(self):
        self.publish_variables = None
        self.installation_variables = None


    def validate_field(self, field_name):
        return getattr(self.__class__, "validate_" + field_name)(self, self.installation_variables[field_name])


    def validate_path(self, path):
        if path == '':
            message = 'Installation path is empty'
            result = False
        elif not os.path.isdir(path):
            message = 'Path doesn\'t exist, check you entered it correctly'
            result = False
        elif not os.path.isdir(os.path.join(path, "SQL")):
            message = 'No SQL directory found, please ensure it exists in the chosen directory'
            result = False
        elif not os.path.isdir(os.path.join(path, "public_html")):
            message = 'No public_html directory found, please ensure it exists in the chosen directory'
            result = False
        else:
            message = 'Path OK'
            result = True

        return result, message


    def validate_site_url(self, url):
        url_regex = r"^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$"

        if url == '':
            message = 'URL is empty'
            result = False
        elif re.match(r"^https?://", url):
            message = 'the URL must be a valid hostname, not including http(s)://'
            result = False
        elif url.startswith("www."):
            message = 'do not start the URL with "www.", this will be added automatically'
            result = False
        elif re.match(url_regex, url) is None:
            message = 'invalid URL'
            result = False
        else:
            message = 'URL OK'
            result = True

        return result, message


    def validate_database(self, db):
        if db['hostname'] == '':
            message = 'Database hostname is empty'
            result = False
        else:
            message = 'Database hostname OK'
            result = True

        return result, message


    def validate_installation_path(self, path):
        return self.validate_path(path)


    def validate_api_key(self, key):
        if key == '':
            message = 'Api key is empty'
            result = False
        else:
            message = 'Api key OK'
            result = True

        return result, message


    def valid(self, field_section, field_variables):
        self.installation_variables = field_variables

        if field_section == 'installation':
            fields_to_check = ['path', 'site_url', 'database']
            success_message = 'Installation fields validated, starting...'
        elif field_section == 'publish':
            self.publish_variables = field_variables

            fields_to_check = ['installation_path', 'site_url', 'api_key']
            success_message = 'Publication fields validated, starting...'

        for field_name in fields_to_check:
            result, message = self.validate_field(field_name)
            if not result:
                return result, message

        return True, success_message

'''
The qt gui class is generated by pyuic5
Due to it being a generated class, it is not edited directly.
Instead, this class wraps around it.
'''

class App(QMainWindow):
    def __init__(self, *args, **kwargs):
        super(App, self).__init__(*args, **kwargs)
        self.init_ui()
        self.publish_variables = {}
        self.installation_variables = {}

        self.threadpool = QThreadPool()
        print("Multithreading with maximum %d threads" % self.threadpool.maxThreadCount())

    def get_installation_variables(self):
        database_variables = {
            'hostname': self.ui.installation_database_hostname_text.text(),
            'username': self.ui.installation_database_username_text.text(),
            'password': self.ui.installation_database_password_text.text()
        }

        self.installation_variables = {
            'path': self.ui.installation_path_text.text(),
            'site_url': self.ui.installation_site_url_text.text(),
            'username': self.ui.installation_username_text.text(),
            #'wordmove_config': self.ui.wordmove_checkbox.isChecked(),
            'database': database_variables
        }

    def get_publish_variables(self):
        self.publish_variables = {
            'cloud_service': 'Digital Ocean',
            'api_key': self.ui.publish_api_key_text.text(),
            'installation_path': self.ui.publish_installation_path_text.text(),
            'site_url': self.ui.publish_site_url_text.text()
        }

    def status_bar_message(self, message):
        timestamp_format = '[%H:%M:%S]'
        timestamp = datetime.datetime.now().strftime(timestamp_format)

        timestamped_message = str(timestamp) + ' ' + message
        self.statusBar().showMessage(timestamped_message)
        self.show()

    def set_installation_path(self):
        dialogue_title = 'Select the folder where you would like to install wordpress'
        folder_name = QFileDialog.getExistingDirectory(self, dialogue_title)
        installation_path = self.ui.installation_path_text
        installation_path.setText(folder_name)

    def set_publish_path(self):
        dialogue_title = 'Select the wordpress installation you would like to publish'
        folder_name = QFileDialog.getExistingDirectory(self, dialogue_title)
        publish_path = self.ui.publish_installation_path_text
        publish_path.setText(folder_name)

    def print_output(self, s):
        print(s)

    def thread_complete(self):
        print("Finished Thread")

    def progress_fn(self, log):
        self.status_bar_message(log)
        self.ui.logs_output_text_box.insertPlainText(log + '\n')

    def start_install(self, progress_callback):
        fields = Fields()
        self.get_installation_variables()
        valid, error_message = fields.valid('installation', self.installation_variables)

        if valid:
            progress_callback.emit('Starting Install')
            installation = wordpress.Wordpress(self.installation_variables)
            installation.start()
            progress_callback.emit('Finished installation')
        else:
            progress_callback.emit(error_message)

    '''
    Check all the fields and other details are there before beginning
    '''
    def start_publish(self, progress_callback):
        fields = Fields()
        self.get_publish_variables()
        valid, error_message = fields.valid('publish', self.publish_variables)

        if valid:
            progress_callback.emit('Publish Fields Validated')
            # Create a new server
            progress_callback.emit('Checking service type')
            if self.publish_variables['cloud_service'] == 'Digital Ocean':
                progress_callback.emit('Using service: ' + self.publish_variables['cloud_service'])
                vps = publish.ServerInit(self.publish_variables)
                username, password = vps.run()

            '''
            Connect to server and perform all necessary configuration
            '''
            progress_callback.emit('Starting configuration')
            vps_configuration = publish.Configuration(username, password, vps, self.publish_variables)
            vps_configuration.run()

            progress_callback.emit('Spun up server. Details are:')
            progress_callback.emit('ipv4 address:' + vps_configuration.ipv4_address)
            progress_callback.emit('username: ' + username)
            progress_callback.emit('password: ' + password)
            progress_callback.emit('Finished Configuration')
            # progress_callback.emit('Uploading files')
        else:
            progress_callback.emit(error_message)

    # TODO the functions below do pretty much the same. Merge into generic
    def publish_trigger(self):
        publication_worker = workers.Worker(self.start_publish)
        publication_worker.signals.finished.connect(self.thread_complete)
        publication_worker.signals.result.connect(self.print_output)
        publication_worker.signals.progress.connect(self.progress_fn)

        self.threadpool.start(publication_worker)

    def install_trigger(self):
        installation_worker = workers.Worker(self.start_install)
        installation_worker.signals.finished.connect(self.thread_complete)
        installation_worker.signals.result.connect(self.print_output)
        installation_worker.signals.progress.connect(self.progress_fn)

        self.threadpool.start(installation_worker)

    def about_dialog(self):
        msg = QMessageBox()

        msg.setWindowTitle("About")
        msg.setText("Author: rs@mage.me.uk\n"
                    "Alpha Build")
        msg.setInformativeText("Let me know if you have any questions. All patches, bug reports and suggestions are most welcome")
        msg.exec_()

    def init_ui(self):
        self.ui = generated.Ui_MainWindow()
        self.ui.setupUi(self)

        # File path selectors
        installation_path_selector = self.ui.installation_path_file_selector
        installation_path_selector.clicked.connect(self.set_installation_path)

        publish_path_selector = self.ui.publish_installation_path_selector
        publish_path_selector.clicked.connect(self.set_publish_path)

        # Start buttons
        installation_start_button = self.ui.installation_start_button
        installation_start_button.clicked.connect(self.install_trigger)

        publish_start_button = self.ui.publish_start_button
        publish_start_button.clicked.connect(self.publish_trigger)

        # About and additional settings buttons
        about_button = self.ui.about_button
        about_button.clicked.connect(self.about_dialog)

        self.show()
