# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\front_end_design_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 442)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.project_title_and_version = QtWidgets.QLabel(self.centralWidget)
        self.project_title_and_version.setGeometry(QtCore.QRect(270, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(14)
        self.project_title_and_version.setFont(font)
        self.project_title_and_version.setObjectName("project_title_and_version")
        self.main_tab = QtWidgets.QTabWidget(self.centralWidget)
        self.main_tab.setGeometry(QtCore.QRect(10, 30, 451, 371))
        self.main_tab.setStyleSheet("")
        self.main_tab.setObjectName("main_tab")
        self.initialize_tab = QtWidgets.QWidget()
        self.initialize_tab.setObjectName("initialize_tab")
        self.installation_site_group_box = QtWidgets.QGroupBox(self.initialize_tab)
        self.installation_site_group_box.setGeometry(QtCore.QRect(10, 10, 411, 151))
        self.installation_site_group_box.setObjectName("installation_site_group_box")
        self.installation_path_file_selector = QtWidgets.QToolButton(self.installation_site_group_box)
        self.installation_path_file_selector.setGeometry(QtCore.QRect(320, 20, 25, 19))
        self.installation_path_file_selector.setObjectName("installation_path_file_selector")
        self.installation_path_text = QtWidgets.QLineEdit(self.installation_site_group_box)
        self.installation_path_text.setGeometry(QtCore.QRect(120, 20, 191, 20))
        self.installation_path_text.setObjectName("installation_path_text")
        self.installation_path_label = QtWidgets.QLabel(self.installation_site_group_box)
        self.installation_path_label.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.installation_path_label.setObjectName("installation_path_label")
        self.installation_username_label = QtWidgets.QLabel(self.installation_site_group_box)
        self.installation_username_label.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.installation_username_label.setObjectName("installation_username_label")
        self.installation_username_text = QtWidgets.QLineEdit(self.installation_site_group_box)
        self.installation_username_text.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.installation_username_text.setObjectName("installation_username_text")
        self.installation_site_name_text = QtWidgets.QLineEdit(self.installation_site_group_box)
        self.installation_site_name_text.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.installation_site_name_text.setObjectName("installation_site_name_text")
        self.installation_site_name = QtWidgets.QLabel(self.installation_site_group_box)
        self.installation_site_name.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self.installation_site_name.setObjectName("installation_site_name")
        self.wordmove_checkbox = QtWidgets.QCheckBox(self.installation_site_group_box)
        self.wordmove_checkbox.setGeometry(QtCore.QRect(280, 100, 111, 17))
        self.wordmove_checkbox.setObjectName("wordmove_checkbox")
        self.installation_site_url = QtWidgets.QLabel(self.installation_site_group_box)
        self.installation_site_url.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.installation_site_url.setObjectName("installation_site_url")
        self.installation_site_url_text = QtWidgets.QLineEdit(self.installation_site_group_box)
        self.installation_site_url_text.setGeometry(QtCore.QRect(120, 50, 191, 20))
        self.installation_site_url_text.setObjectName("installation_site_url_text")
        self.installation_database_group_box = QtWidgets.QGroupBox(self.initialize_tab)
        self.installation_database_group_box.setGeometry(QtCore.QRect(10, 170, 411, 101))
        self.installation_database_group_box.setObjectName("installation_database_group_box")
        self.installation_database_hostname_label = QtWidgets.QLabel(self.installation_database_group_box)
        self.installation_database_hostname_label.setGeometry(QtCore.QRect(20, 30, 51, 16))
        self.installation_database_hostname_label.setObjectName("installation_database_hostname_label")
        self.installation_database_hostname_text = QtWidgets.QLineEdit(self.installation_database_group_box)
        self.installation_database_hostname_text.setGeometry(QtCore.QRect(80, 30, 151, 20))
        self.installation_database_hostname_text.setObjectName("installation_database_hostname_text")
        self.installation_database_password_text = QtWidgets.QLineEdit(self.installation_database_group_box)
        self.installation_database_password_text.setGeometry(QtCore.QRect(280, 60, 113, 20))
        self.installation_database_password_text.setObjectName("installation_database_password_text")
        self.installation_database_username_text = QtWidgets.QLineEdit(self.installation_database_group_box)
        self.installation_database_username_text.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.installation_database_username_text.setObjectName("installation_database_username_text")
        self.installation_database_username_label = QtWidgets.QLabel(self.installation_database_group_box)
        self.installation_database_username_label.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.installation_database_username_label.setObjectName("installation_database_username_label")
        self.installation_database_password_label = QtWidgets.QLabel(self.installation_database_group_box)
        self.installation_database_password_label.setGeometry(QtCore.QRect(220, 60, 61, 20))
        self.installation_database_password_label.setObjectName("installation_database_password_label")
        self.installation_start_button = QtWidgets.QPushButton(self.initialize_tab)
        self.installation_start_button.setGeometry(QtCore.QRect(320, 290, 91, 31))
        self.installation_start_button.setObjectName("installation_start_button")
        self.main_tab.addTab(self.initialize_tab, "")
        self.publish_tab = QtWidgets.QWidget()
        self.publish_tab.setObjectName("publish_tab")
        self.publish_host_group_box = QtWidgets.QGroupBox(self.publish_tab)
        self.publish_host_group_box.setGeometry(QtCore.QRect(10, 100, 401, 131))
        self.publish_host_group_box.setObjectName("publish_host_group_box")
        self.publish_api_key_label = QtWidgets.QLabel(self.publish_host_group_box)
        self.publish_api_key_label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.publish_api_key_label.setObjectName("publish_api_key_label")
        self.publish_api_key_text = QtWidgets.QLineEdit(self.publish_host_group_box)
        self.publish_api_key_text.setGeometry(QtCore.QRect(110, 30, 271, 20))
        self.publish_api_key_text.setObjectName("publish_api_key_text")
        self.publish_installation_path_label = QtWidgets.QLabel(self.publish_host_group_box)
        self.publish_installation_path_label.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.publish_installation_path_label.setObjectName("publish_installation_path_label")
        self.publish_installation_path_text = QtWidgets.QLineEdit(self.publish_host_group_box)
        self.publish_installation_path_text.setGeometry(QtCore.QRect(110, 60, 231, 20))
        self.publish_installation_path_text.setObjectName("publish_installation_path_text")
        self.publish_installation_path_selector = QtWidgets.QToolButton(self.publish_host_group_box)
        self.publish_installation_path_selector.setGeometry(QtCore.QRect(350, 60, 25, 19))
        self.publish_installation_path_selector.setObjectName("publish_installation_path_selector")
        self.publish_site_url_label = QtWidgets.QLabel(self.publish_host_group_box)
        self.publish_site_url_label.setGeometry(QtCore.QRect(20, 90, 71, 16))
        self.publish_site_url_label.setObjectName("publish_site_url_label")
        self.publish_site_url_text = QtWidgets.QLineEdit(self.publish_host_group_box)
        self.publish_site_url_text.setGeometry(QtCore.QRect(110, 90, 271, 20))
        self.publish_site_url_text.setObjectName("publish_site_url_text")
        self.publish_start_button = QtWidgets.QPushButton(self.publish_tab)
        self.publish_start_button.setGeometry(QtCore.QRect(320, 290, 91, 31))
        self.publish_start_button.setObjectName("publish_start_button")
        self.main_tab.addTab(self.publish_tab, "")
        self.logs_tab = QtWidgets.QWidget()
        self.logs_tab.setObjectName("logs_tab")
        self.logs_output_group_box = QtWidgets.QGroupBox(self.logs_tab)
        self.logs_output_group_box.setGeometry(QtCore.QRect(10, 20, 411, 311))
        self.logs_output_group_box.setObjectName("logs_output_group_box")
        self.logs_output_text_box = QtWidgets.QTextBrowser(self.logs_output_group_box)
        self.logs_output_text_box.setGeometry(QtCore.QRect(10, 30, 391, 271))
        self.logs_output_text_box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.logs_output_text_box.setObjectName("logs_output_text_box")
        self.main_tab.addTab(self.logs_tab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 471, 21))
        self.menuBar.setObjectName("menuBar")
        self.menufile = QtWidgets.QMenu(self.menuBar)
        self.menufile.setObjectName("menufile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAdditional_Setings = QtWidgets.QMenu(self.menuBar)
        self.menuAdditional_Setings.setObjectName("menuAdditional_Setings")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menufile.addAction(self.actionexit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuAdditional_Setings.addAction(self.actionSettings)
        self.menuBar.addAction(self.menufile.menuAction())
        self.menuBar.addAction(self.menuAdditional_Setings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.project_title_and_version.setText(_translate("MainWindow", "WP Publisher v0.1"))
        self.installation_site_group_box.setTitle(_translate("MainWindow", "Site"))
        self.installation_path_file_selector.setText(_translate("MainWindow", "..."))
        self.installation_path_label.setText(_translate("MainWindow", "Installation Path"))
        self.installation_username_label.setText(_translate("MainWindow", "Username"))
        self.installation_site_name.setText(_translate("MainWindow", "Site Name"))
        self.wordmove_checkbox.setText(_translate("MainWindow", "Wordmove config"))
        self.installation_site_url.setText(_translate("MainWindow", "Site Url"))
        self.installation_database_group_box.setTitle(_translate("MainWindow", "Database"))
        self.installation_database_hostname_label.setText(_translate("MainWindow", "Hostname"))
        self.installation_database_username_label.setText(_translate("MainWindow", "Username"))
        self.installation_database_password_label.setText(_translate("MainWindow", "Password"))
        self.installation_start_button.setText(_translate("MainWindow", "Start"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.initialize_tab), _translate("MainWindow", "Initialize"))
        self.publish_host_group_box.setTitle(_translate("MainWindow", "Host"))
        self.publish_api_key_label.setText(_translate("MainWindow", "API Key"))
        self.publish_installation_path_label.setText(_translate("MainWindow", "Installation Path"))
        self.publish_installation_path_selector.setText(_translate("MainWindow", "..."))
        self.publish_site_url_label.setText(_translate("MainWindow", "Site Url"))
        self.publish_start_button.setText(_translate("MainWindow", "Start"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.publish_tab), _translate("MainWindow", "Publish"))
        self.logs_output_group_box.setTitle(_translate("MainWindow", "Output"))
        self.logs_output_text_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.logs_tab), _translate("MainWindow", "Logs"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAdditional_Setings.setTitle(_translate("MainWindow", "Edit"))
        self.actionexit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "AdditionalSettings"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

