# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\front_end_design.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 414)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 440, 381))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(330, 300, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 411, 151))
        self.groupBox.setObjectName("groupBox")
        self.installation_path_file_selector = QtWidgets.QToolButton(self.groupBox)
        self.installation_path_file_selector.setGeometry(QtCore.QRect(320, 20, 25, 19))
        self.installation_path_file_selector.setObjectName("installation_path_file_selector")
        self.installation_path_text = QtWidgets.QLineEdit(self.groupBox)
        self.installation_path_text.setGeometry(QtCore.QRect(120, 20, 191, 20))
        self.installation_path_text.setObjectName("installation_path_text")
        self.installation_path_label = QtWidgets.QLabel(self.groupBox)
        self.installation_path_label.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.installation_path_label.setObjectName("installation_path_label")
        self.installation_username_label = QtWidgets.QLabel(self.groupBox)
        self.installation_username_label.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.installation_username_label.setObjectName("installation_username_label")
        self.installation_username_text = QtWidgets.QLineEdit(self.groupBox)
        self.installation_username_text.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.installation_username_text.setObjectName("installation_username_text")
        self.installation_site_name_text = QtWidgets.QLineEdit(self.groupBox)
        self.installation_site_name_text.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.installation_site_name_text.setObjectName("installation_site_name_text")
        self.installation_site_name = QtWidgets.QLabel(self.groupBox)
        self.installation_site_name.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self.installation_site_name.setObjectName("installation_site_name")
        self.wordmove = QtWidgets.QCheckBox(self.groupBox)
        self.wordmove.setGeometry(QtCore.QRect(280, 100, 111, 17))
        self.wordmove.setObjectName("wordmove")
        self.installation_site_url = QtWidgets.QLabel(self.groupBox)
        self.installation_site_url.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.installation_site_url.setObjectName("installation_site_url")
        self.installation_site_url_text = QtWidgets.QLineEdit(self.groupBox)
        self.installation_site_url_text.setGeometry(QtCore.QRect(120, 50, 191, 20))
        self.installation_site_url_text.setObjectName("installation_site_url_text")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 280, 301, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.installation_progress_progress_bar = QtWidgets.QProgressBar(self.groupBox_2)
        self.installation_progress_progress_bar.setGeometry(QtCore.QRect(180, 20, 115, 23))
        self.installation_progress_progress_bar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.installation_progress_progress_bar.setProperty("value", 0)
        self.installation_progress_progress_bar.setObjectName("installation_progress_progress_bar")
        self.installation_progress_current_status = QtWidgets.QLabel(self.groupBox_2)
        self.installation_progress_current_status.setGeometry(QtCore.QRect(20, 20, 141, 21))
        self.installation_progress_current_status.setObjectName("installation_progress_current_status")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 411, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 51, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 30, 151, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(280, 60, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(220, 60, 61, 20))
        self.label_9.setObjectName("label_9")
        self.groupBox_2.raise_()
        self.pushButton.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 100, 401, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_8.setGeometry(QtCore.QRect(110, 30, 271, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(110, 60, 231, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_2.setGeometry(QtCore.QRect(350, 60, 25, 19))
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 71, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 90, 271, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 290, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 411, 321))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 391, 281))
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 20, 391, 71))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 361, 21))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_4, "")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "WP Publisher"))
        self.pushButton.setText(_translate("Dialog", "Start"))
        self.groupBox.setTitle(_translate("Dialog", "Site"))
        self.installation_path_file_selector.setText(_translate("Dialog", "..."))
        self.installation_path_label.setText(_translate("Dialog", "Installation Path"))
        self.installation_username_label.setText(_translate("Dialog", "Username"))
        self.installation_site_name.setText(_translate("Dialog", "Site Name"))
        self.wordmove.setText(_translate("Dialog", "Wordmove config"))
        self.installation_site_url.setText(_translate("Dialog", "Site Url"))
        self.groupBox_2.setTitle(_translate("Dialog", "Installation Progress"))
        self.installation_progress_current_status.setText(_translate("Dialog", "Currently Idle"))
        self.groupBox_3.setTitle(_translate("Dialog", "Database"))
        self.label_7.setText(_translate("Dialog", "Hostname"))
        self.label_8.setText(_translate("Dialog", "Username"))
        self.label_9.setText(_translate("Dialog", "Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Initialize"))
        self.groupBox_5.setTitle(_translate("Dialog", "Host"))
        self.label_10.setText(_translate("Dialog", "API Key"))
        self.label_11.setText(_translate("Dialog", "Installation Path"))
        self.toolButton_2.setText(_translate("Dialog", "..."))
        self.label_12.setText(_translate("Dialog", "Site Url"))
        self.pushButton_2.setText(_translate("Dialog", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Publish"))
        self.groupBox_4.setTitle(_translate("Dialog", "Output"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test 123</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Logs"))
        self.groupBox_6.setTitle(_translate("Dialog", "Help"))
        self.label_13.setText(_translate("Dialog", "Please see readme"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Help"))
        self.label.setText(_translate("Dialog", "WP Publisher v0.1"))

